// Code generated by "stringer -type=AssertionType"; DO NOT EDIT.

package httpexpect

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _AssertionType_name = "AssertUsageAssertOperationAssertTypeAssertNotTypeAssertValidAssertNotValidAssertNilAssertNotNilAssertEmptyAssertNotEmptyAssertEqualAssertNotEqualAssertLtAssertLeAssertGtAssertGeAssertInRangeAssertNotInRangeAssertMatchSchemaAssertNotMatchSchemaAssertMatchPathAssertNotMatchPathAssertMatchRegexpAssertNotMatchRegexpAssertMatchFormatAssertNotMatchFormatAssertContainsKeyAssertNotContainsKeyAssertContainsElementAssertNotContainsElementAssertContainsSubsetAssertNotContainsSubsetAssertBelongsAssertNotBelongs"

var _AssertionType_index = [...]uint16{0, 11, 26, 36, 49, 60, 74, 83, 95, 106, 120, 131, 145, 153, 161, 169, 177, 190, 206, 223, 243, 258, 276, 293, 313, 330, 350, 367, 387, 408, 432, 452, 475, 488, 504}

func (i AssertionType) String() string { _ = "STUB: not implemented"; return "" }
