// Code generated by "stringer -type=AssertionSeverity"; DO NOT EDIT.

package httpexpect

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _AssertionSeverity_name = "SeverityErrorSeverityLog"

var _AssertionSeverity_index = [...]uint8{0, 13, 24}

func (i AssertionSeverity) String() string { _ = "STUB: not implemented"; return "" }
